export default {
  en: {
    create: 'Create',
    save: 'save',
    cancel: 'cancel',
    add: 'Add',
    modify: 'Modify',
    delete: 'Delete',
    authority: 'Authority',
    Cancel: 'Cancel',
    title_Add: 'Add Dimension',
    title_Modify: 'Modify Dimension',
    title_Authority: 'Authority',
    ParentNodeName: 'Parent Node',
    Name: 'Dimension Name',
    Name_RM: 'please input dimension name.',
    PrincipalId: 'Dimension Id',
    Order: 'Order',
    Order_RM: 'please input order.',
    Description: 'Description',
    ModifyTime: 'Modify Time',
    ModifyUser: 'Modify User',
    deleteConfirm: 'Are you sure delete this node?',
    Authorized: 'authorized',
    Unauthorized: 'unauthorized',
    IsInherit: 'Inherit',
    Inherit: 'Inherit',
  },
  zh: {
    create: '创建',
    add: '新增',
    save: '保存',
    cancel: '取消',
    Cancel: '取消',
    modify: '修改',
    delete: '删除',
    authority: '授权',
    title_Add: '新增维度',
    title_Modify: '修改维度',
    title_Authority: '权限设置',
    ParentNodeName: '父节点',
    Name: '维度名称',
    Name_RM: '请输入维度名称，同级维度名称不可重复..',
    PrincipalId: '维度ID',
    Order: '序号',
    Order_RM: '请输入序号.',
    Description: '简介',
    ModifyTime: '更新时间',
    ModifyUser: '更新人',
    deleteConfirm: '确定删除此节点？',
    Authorized: '已授权',
    Unauthorized: '未授权',
    IsInherit: '是否继承',
    Inherit: '继承',
  },
};
