export default {
  en: {
    add: 'Add',
    save: 'save',
    cancel: 'cancel',
    title_Add: 'User Add',
    title_Modify: 'User Modify',
    Name: 'User Name',
    Name_RM: 'please input user name.',
    NameEn: 'User Name(en)',
    User_Account: 'User Account',
    User_Account_RM: 'please input user account.',
    User_Sex: 'sex',
    male: 'male',
    female: 'female',
    User_Age: 'age',
    User_Age_RM: 'please input age.',
    User_Email: 'Email',
    User_Email_RM: 'please input email address.',
    User_Title: 'Title',
    User_Address: 'Address',
    Description: 'Description',
    ModifyTime: 'Modify Time',
    ModifyUser: 'Modify User',
    searchPlaceHolder: 'User Name,User ID',
    deleteConfirmTitle: 'Are you sure delete this user?',
  },
  zh: {
    add: '新增',
    save: '保存',
    cancel: '取消',
    title_Add: '新增用户',
    title_Modify: '修改用户',
    Name: '用户名',
    Name_RM: '请输入中文名.',
    NameEn: '英文名',
    User_Account: '用户工号',
    User_Account_RM: '请输入用户工号.',
    User_Sex: '性别',
    male: '男',
    female: '女',
    User_Age: '年龄',
    User_Age_RM: '请输入年龄.',
    User_Email: '邮箱',
    User_Email_RM: '请输入邮箱.',
    User_Title: '职务',
    User_Address: '地址',
    Description: '用户简介',
    ModifyTime: '更新时间',
    ModifyUser: '更新人',
    searchPlaceHolder: '用户名、用户工号',
    deleteConfirmTitle: '确定删除此用户?',
  },
};
