export default {
  en: {
    add: 'Add',
    save: 'save',
    cancel: 'cancel',
    title: 'Data Authority',
    Authority: 'Authority',
    Name: 'Name',
    PrincipalType: 'Type',
    User: 'user',
    Role: 'role',
    Description: 'Description',
    ModifyTime: 'Modify Time',
    ModifyUser: 'Modify User',
    searchPlaceHolder: 'Role Name,User Name,User ID',
  },
  zh: {
    add: '新增',
    save: '保存',
    cancel: '取消',
    title: '维度授权',
    Authority: '设置维度权限',
    Name: '名称',
    PrincipalType: '类型',
    User: '用户',
    Role: '角色',
    Description: '简介',
    ModifyTime: '更新时间',
    ModifyUser: '更新人',
    searchPlaceHolder: '角色名称，用户名，用户工号',
  },
};
