export default {
  en: {
    add: 'Add',
    save: 'save',
    cancel: 'cancel',
    create: 'Create',
    modify: 'Modify',
    delete: 'Delete',
    Cancel: 'Cancel',
    authority: 'Authority',
    Authority: 'Authority',
    deleteConfirm: 'Are you sure delete this node?',
    Authorized: 'authorized',
    Unauthorized: 'unauthorized',

    user_title_Add: 'User Add',
    user_title_Modify: 'User Modify',
    user_Name: 'User Name',
    user_Name_RM: 'please input user name.',
    user_NameEn: 'User Name(en)',
    user_User_Account: 'User Account',
    user_User_Account_RM: 'please input user account.',
    user_User_Sex: 'sex',
    user_male: 'male',
    user_female: 'female',
    user_User_Age: 'age',
    user_User_Age_RM: 'please input age.',
    user_User_Email: 'Email',
    user_User_Email_RM: 'please input email address.',
    user_User_Title: 'Title',
    user_User_Address: 'Address',
    user_Description: 'Description',
    user_ModifyTime: 'Modify Time',
    user_ModifyUser: 'Modify User',
    user_searchPlaceHolder: 'User Name,User ID',
    user_deleteConfirmTitle: 'Are you sure delete this user?',

    role_title_Add: 'Role Add',
    role_title_Modify: 'Role Modify',
    role_Name: 'Role Name',
    role_Name_RM: 'please input role name.',
    role_Description: 'Description',
    role_ModifyTime: 'Modify Time',
    role_ModifyUser: 'Modify User',
    role_searchPlaceHolder: 'Role Name',
    role_deleteConfirmTitle: 'Are you sure delete this role?',
    role_setUsers: 'Set Users',

    menu_authority: 'Authority',
    menu_Cancel: 'Cancel',
    menu_title_Add: 'Add Menu',
    menu_title_Modify: 'Modify Menu',
    menu_title_Authority: 'Authority',
    menu_ParentNodeName: 'Parent Node',
    menu_App_Id: 'App',
    menu_App_Id_RM: 'please select app.',
    menu_Name: 'Menu Name',
    menu_Name_RM: 'please input Menu name.',
    menu_PrincipalId: 'Menu Id',
    menu_Order: 'Order',
    menu_Order_RM: 'please input order.',
    menu_Description: 'Description',
    menu_M_Url: 'Url',
    menu_M_Url_RM: 'please input url.',
    menu_M_AppendUrl: 'Append Url',
    menu_M_Icon: 'Icon',
    menu_M_IsEnable: 'Enable',
    menu_M_IsVisible: 'Visible',
    menu_Enable: 'Enable',
    menu_Visible: 'Visible',
    menu_ModifyTime: 'Modify Time',
    menu_ModifyUser: 'Modify User',
    menu_deleteConfirm: 'Are you sure delete this node?',
    menu_Authorized: 'authorized',
    menu_Unauthorized: 'unauthorized',
    menu_IsInherit: 'Inherit',
    menu_Inherit: 'Inherit',

    fa_title: 'Function Authority',
    fa_Authority: 'Authority',
    fa_Name: 'Name',
    fa_PrincipalType: 'Type',
    fa_User: 'user',
    fa_Role: 'role',
    fa_Description: 'Description',
    fa_ModifyTime: 'Modify Time',
    fa_ModifyUser: 'Modify User',
    fa_searchPlaceHolder: 'Role Name,User Name,User ID',

    dim_authority: 'Authority',
    dim_Cancel: 'Cancel',
    dim_title_Add: 'Add Dimension',
    dim_title_Modify: 'Modify Dimension',
    dim_title_Authority: 'Authority',
    dim_ParentNodeName: 'Parent Node',
    dim_Name: 'Dimension Name',
    dim_Name_RM: 'please input dimension name.',
    dim_PrincipalId: 'Dimension Id',
    dim_Order: 'Order',
    dim_Order_RM: 'please input order.',
    dim_Description: 'Description',
    dim_ModifyTime: 'Modify Time',
    dim_ModifyUser: 'Modify User',
    dim_deleteConfirm: 'Are you sure delete this node?',
    dim_Authorized: 'authorized',
    dim_Unauthorized: 'unauthorized',
    dim_IsInherit: 'Inherit',
    dim_Inherit: 'Inherit',

    da_title: 'Data Authority',
    da_Authority: 'Authority',
    da_Name: 'Name',
    da_PrincipalType: 'Type',
    da_User: 'user',
    da_Role: 'role',
    da_Description: 'Description',
    da_ModifyTime: 'Modify Time',
    da_ModifyUser: 'Modify User',
    da_searchPlaceHolder: 'Role Name,User Name,User ID',

    index_name: 'Sharewinfo',
    index_portal: 'Home',
  },
  zh: {
    add: '新增',
    save: '保存',
    cancel: '取消',
    create: '创建',
    Cancel: '取消',
    modify: '修改',
    delete: '删除',
    authority: '授权',
    Authority: '权限设置',
    deleteConfirm: '确定删除此节点？',
    Authorized: '已授权',
    Unauthorized: '未授权',

    user_title_Add: '新增用户',
    user_title_Modify: '修改用户',
    user_Name: '用户名',
    user_Name_RM: '请输入中文名.',
    user_NameEn: '英文名',
    user_User_Account: '用户工号',
    user_User_Account_RM: '请输入用户工号.',
    user_User_Sex: '性别',
    user_male: '男',
    user_female: '女',
    user_User_Age: '年龄',
    user_User_Age_RM: '请输入年龄.',
    user_User_Email: '邮箱',
    user_User_Email_RM: '请输入邮箱.',
    user_User_Title: '职务',
    user_User_Address: '地址',
    user_Description: '用户简介',
    user_ModifyTime: '更新时间',
    user_ModifyUser: '更新人',
    user_searchPlaceHolder: '用户名、用户工号',
    user_deleteConfirmTitle: '确定删除此用户?',

    role_title_Add: '新增角色',
    role_title_Modify: '修改角色',
    role_Name: '角色名',
    role_Name_RM: '请输入角色名称',
    role_Description: '简介',
    role_ModifyTime: '更新时间',
    role_ModifyUser: '更新人',
    role_searchPlaceHolder: '角色名',
    role_deleteConfirmTitle: '确定删除此角色?',
    role_setUsers: '设置用户',

    menu_authority: '授权',
    menu_title_Add: '新增菜单',
    menu_title_Modify: '修改菜单',
    menu_title_Authority: '权限设置',
    menu_ParentNodeName: '父节点',
    menu_App_Id: '应用名称',
    menu_App_Id_RM: '请选择系统应用.',
    menu_Name: '菜单名称',
    menu_Name_RM: '请输入菜单名称，同级菜单名称不可重复.',
    menu_PrincipalId: '菜单ID',
    menu_M_Url: '菜单Url',
    menu_M_Url_RM: '请输入菜单Url.',
    menu_M_AppendUrl: '附加Url',
    menu_M_Icon: '菜单图标',
    menu_Order: '序号',
    menu_Order_RM: '请输入序号.',
    menu_Description: '简介',
    menu_M_IsEnable: '是否启用',
    menu_M_IsVisible: '是否可见',
    menu_Enable: '启用',
    menu_Visible: '可见',
    menu_ModifyTime: '更新时间',
    menu_ModifyUser: '更新人',
    menu_deleteConfirm: '确定删除此节点？',
    menu_Authorized: '已授权',
    menu_Unauthorized: '未授权',
    menu_IsInherit: '是否继承',
    menu_Inherit: '继承',

    fa_title: '功能授权',
    fa_Authority: '设置功能权限',
    fa_Name: '名称',
    fa_PrincipalType: '类型',
    fa_User: '用户',
    fa_Role: '角色',
    fa_Description: '简介',
    fa_ModifyTime: '更新时间',
    fa_ModifyUser: '更新人',
    fa_searchPlaceHolder: '角色名称，用户名，用户工号',

    dim_authority: '授权',
    dim_title_Add: '新增维度',
    dim_title_Modify: '修改维度',
    dim_title_Authority: '权限设置',
    dim_ParentNodeName: '父节点',
    dim_Name: '维度名称',
    dim_Name_RM: '请输入维度名称，同级维度名称不可重复..',
    dim_PrincipalId: '维度ID',
    dim_Order: '序号',
    dim_Order_RM: '请输入序号.',
    dim_Description: '简介',
    dim_ModifyTime: '更新时间',
    dim_ModifyUser: '更新人',
    dim_deleteConfirm: '确定删除此节点？',
    dim_Authorized: '已授权',
    dim_Unauthorized: '未授权',
    dim_IsInherit: '是否继承',
    dim_Inherit: '继承',

    da_Authority: '设置维度权限',
    da_Name: '名称',
    da_PrincipalType: '类型',
    da_User: '用户',
    da_Role: '角色',
    da_Description: '简介',
    da_ModifyTime: '更新时间',
    da_ModifyUser: '更新人',
    da_searchPlaceHolder: '角色名称，用户名，用户工号',

    index_name: '上北智信',
    index_portal: '首页',
  },
};
