export default {
  searchPlaceHolder: 'Menu Name,Menu Url',
  add: '/api/Menu/Add',
  update: '/api/Menu/Update',
  delete: '/api/Menu/Delete',
  search: '/api/Menu/Get',
  getCurrentPrincipals: '/api/FunctionalAuthority/GetCurrentPrincipals',
  setPrincipals: '/api/FunctionalAuthority/SetPrincipals',
  deleteConfirmTitle: 'Are you sure delete this Menu?',
  defaultModel: {
    PrincipalId: '',
    Name: '',
    NameEn: '',
    Description: '',
    ParentNode: '',
    ParentNodeName: '',
    ModifyTime: '',
    ModifyUser: '',
    App_Id: '',
    M_Url: '',
    M_Level2: '',
    M_AppendUrl: '',
    M_Icon: '',
    M_IsEnable: '',
    M_IsVisible: '',
  },
};
