export default {
  en: {
    create: 'Create',
    save: 'save',
    cancel: 'cancel',
    add: 'Add',
    modify: 'Modify',
    delete: 'Delete',
    authority: 'Authority',
    Cancel: 'Cancel',
    title_Add: 'Add Menu',
    title_Modify: 'Modify Menu',
    title_Authority: 'Authority',
    ParentNodeName: 'Parent Node',
    App_Id: 'App',
    App_Id_RM: 'please select app.',
    Name: 'Menu Name',
    Name_RM: 'please input Menu name.',
    PrincipalId: 'Menu Id',
    Order: 'Order',
    Order_RM: 'please input order.',
    Description: 'Description',
    M_Url: 'Url',
    M_Url_RM: 'please input url.',
    M_AppendUrl: 'Append Url',
    M_Icon: 'Icon',
    M_IsEnable: 'Enable',
    M_IsVisible: 'Visible',
    Enable: 'Enable',
    Visible: 'Visible',
    ModifyTime: 'Modify Time',
    ModifyUser: 'Modify User',
    deleteConfirm: 'Are you sure delete this node?',
    Authorized: 'authorized',
    Unauthorized: 'unauthorized',
    IsInherit: 'Inherit',
    Inherit: 'Inherit',
  },
  zh: {
    create: '创建',
    add: '新增',
    save: '保存',
    cancel: '取消',
    Cancel: '取消',
    modify: '修改',
    delete: '删除',
    authority: '授权',
    title_Add: '新增菜单',
    title_Modify: '修改菜单',
    title_Authority: '权限设置',
    ParentNodeName: '父节点',
    App_Id: '应用名称',
    App_Id_RM: '请选择系统应用.',
    Name: '菜单名称',
    Name_RM: '请输入菜单名称，同级菜单名称不可重复.',
    PrincipalId: '菜单ID',
    M_Url: '菜单Url',
    M_Url_RM: '请输入菜单Url.',
    M_AppendUrl: '附加Url',
    M_Icon: '菜单图标',
    Order: '序号',
    Order_RM: '请输入序号.',
    Description: '简介',
    M_IsEnable: '是否启用',
    M_IsVisible: '是否可见',
    Enable: '启用',
    Visible: '可见',
    ModifyTime: '更新时间',
    ModifyUser: '更新人',
    deleteConfirm: '确定删除此节点？',
    Authorized: '已授权',
    Unauthorized: '未授权',
    IsInherit: '是否继承',
    Inherit: '继承',
  },
};
