export default {
  en: {
    add: 'Add',
    save: 'save',
    cancel: 'cancel',
    title_Add: 'Role Add',
    title_Modify: 'Role Modify',
    Name: 'Role Name',
    Name_RM: 'please input role name.',
    Description: 'Description',
    ModifyTime: 'Modify Time',
    ModifyUser: 'Modify User',
    searchPlaceHolder: 'Role Name',
    deleteConfirmTitle: 'Are you sure delete this role?',
    setUsers: 'Set Users',
  },
  zh: {
    add: '新增',
    save: '保存',
    cancel: '取消',
    title_Add: '新增角色',
    title_Modify: '修改角色',
    Name: '角色名',
    Name_RM: '请输入角色名称',
    Description: '简介',
    ModifyTime: '更新时间',
    ModifyUser: '更新人',
    searchPlaceHolder: '角色名',
    deleteConfirmTitle: '确定删除此角色?',
    setUsers: '设置用户',
  },
};
